### ISSUE TITLE
Visualize a label from PPP

### ISSUE THREAD

**Issue by Njuod** [tue-mps/panoptic_parts#26]
Hi, thank you for your interesting work. 

I would like to visualize a label from PPP  but I do not know how to fold groupable parts, I read `ppp_datasetspec.yaml` but I am a little lost, is it by applying  `countable_pids_groupings`? I'd be glad if you could tell me how to do that. Thanks.

**Comment by pmeletis** [comment]
Hi Njuod, you can browse the [visualize_label_with_legend.py](https://github.com/pmeletis/panoptic_parts/blob/45f7121cf2d4bfe65e6dc27b3f006d1104841ae1/panoptic_parts/visualization/visualize_label_with_legend.py) script to see how we visualize the labels. Basically, the [`decode_uids`](https://github.com/pmeletis/panoptic_parts/blob/45f7121cf2d4bfe65e6dc27b3f006d1104841ae1/panoptic_parts/visualization/visualize_label_with_legend.py#L37) function is doing the groupable parts folding, and then the [`colorize_label`](https://github.com/pmeletis/panoptic_parts/blob/45f7121cf2d4bfe65e6dc27b3f006d1104841ae1/panoptic_parts/visualization/visualize_label_with_legend.py#L39) function assigns colors to the uids. For more details on how we unify the part ids of all groupable parts to a single part id see [here](https://github.com/pmeletis/panoptic_parts/blob/45f7121cf2d4bfe65e6dc27b3f006d1104841ae1/panoptic_parts/utils/format.py#L229).

**Comment by Njuod** [comment]
Hi pmeletis,

Thanks for your reply.
I am trying to visualize labels from a folder so I have modified the  visualize_label_with_legend.py by using for loop, but I got this error:
```
Traceback (most recent call last):
  File "Desktop/.../panoptic_parts/panoptic_parts/visualization/visualize_label_with_legend.py", line 87, in <module>
    main()
  File "Desktop/.../panoptic_parts/panoptic_parts/visualization/visualize_label_with_legend.py", line 81, in main
    visualize_from_paths(args.datasetspec_path, args.label_path)
  File "Desktop/.../panoptic_parts/panoptic_parts/visualization/visualize_label_with_legend.py", line 48, in visualize_from_paths
    uids_sem_inst_parts_colored, uid2color_dct = experimental_colorize_label(
  File "Desktop/.../panoptic_parts/panoptic_parts/utils/visualization.py", line 377, in experimental_colorize_label
    uid2color_dict = uid2color(ids_all_levels_unique, sid2color=sid2color,
  File "Desktop/.../panoptic_parts/panoptic_parts/utils/visualization.py", line 321, in uid2color
    index_pid = sid_2_non_zero_pids[sid].index(pid)
ValueError: 7 is not in list
```
Could you help me to solve this error? Many thanks.

**Comment by pmeletis** [comment]
Are the labels you want to visualize, the ground truth we provide, or labels from your predictions? Also, it will help to share the filename of the labels (if the first case is true)?

**Comment by Njuod** [comment]
Yes, I am trying to visualize the ground truth you provide (validation set). The filename of the labels is *.tif as in the validation set. Here is the modified part of the code:

```
  spec = DatasetSpec(datasetspec_path)

  labels = glob.glob(os.path.join(label_path,'*.tif'))
  for label in labels:
      label_path = str(label)
      name = os.path.split(label_path)
      file_path = os.path.join('ppp_gt/', name[1].split('/')[-1].replace('.tif','.png')) 

      uids = np.array(Image.open(label_path), dtype=np.int32)
      uids = encode_ids(*decode_uids(uids, experimental_dataset_spec=spec, experimental_correct_range=True))

      uids_sem_inst_parts_colored, uid2color_dct = experimental_colorize_label(
          uids, sid2color=spec.sid2scene_color, emphasize_instance_boundaries=True, return_uid2color=False,
          experimental_deltas=(60, 60, 60), experimental_alpha=0.5)

      # plot
      _, ax1 = plt.subplots()

      # generate legend, h is a hidden rectangle just to create a legend entry
      handles = []
      handles_text = []
      uids_unique = np.unique(uids)
      for uid in uids_unique:
        h = plt.Rectangle((0, 0), 1, 1, fc=list(map(lambda x: x/255, uid2color_dct[uid])))
        handles.append(h)
        _, _, _, sid_pid = decode_uids(uid, return_sids_pids=True)
        scene_class_part_class = spec.scene_class_part_class_from_sid_pid(sid_pid)
        handles_text.append(f'{uid}: {scene_class_part_class}')

      ax1.imshow(uids_sem_inst_parts_colored)
      #ax1.set_title('labels colored on semantic, instance, and part levels', fontsize='small')
      #ax1.legend(handles, handles_text, ncol=3, fontsize='small', handlelength=1.0,
      #           loc='center left', bbox_to_anchor=(1.01, 0.5))
      plt.tight_layout()
      #plt.show()
      plt.axis('off')
      plt.savefig(file_path, dpi=300, bbox_inches='tight', pad_inches = 0)

```

**Comment by pmeletis** [comment]
Dear Njuod, as a fast fix set the legacy color map to False using the following lines:

```python
from panoptic_parts.utils.visualization import set_use_legacy_cpp_parts_colormap
set_use_legacy_cpp_parts_colormap(False)
```

This will solve the issue till I commit the fix.

**Comment by Njuod** [comment]
Great, thank you for your help.
